// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygctsplkylhyzdycslzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnY3RzcGxreWxoeXpkeWNzbHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDI3NDksImV4cCI6MjA2NzExODc0OX0.k1hXaelF4QNr6-vM-NifcYwfFGuGwx5JfojNaeNwgSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});